### ISSUE TITLE
Html report incomplete due to some errors

### ISSUE THREAD

**Issue by 103683** [PragmaticFlow/NBomber#264] opened 2020-11-20 13:40 UTC
![image](https://user-images.githubusercontent.com/21205221/99806246-6a88fe00-2b46-11eb-868d-fea7e9c85a5f.png)

First error from console:
vue@2.6.11:6 TypeError: Cannot read property 'RPS' of undefined
    at custom_report_name_2020-11-20--13-19-04.html:737
    at Array.map (<anonymous>)
    at createSeriesDataStepStats (custom_report_name_2020-11-20--13-19-04.html:737)
    at createSettingsChartStepThroughput (custom_report_name_2020-11-20--13-19-04.html:1001)
    at a.mounted (custom_report_name_2020-11-20--13-19-04.html:1237)
    at He (vue@2.6.11:6)
    at Yt (vue@2.6.11:6)
    at Object.insert (vue@2.6.11:6)
    at k (vue@2.6.11:6)
    at a.__patch__ (vue@2.6.11:6)

Second error from console:
vue@2.6.11:6 TypeError: Cannot read property 'Min' of undefined
    at custom_report_name_2020-11-20--13-19-04.html:737
    at Array.map (<anonymous>)
    at createSeriesDataStepStats (custom_report_name_2020-11-20--13-19-04.html:737)
    at createSettingsChartStepLatency (custom_report_name_2020-11-20--13-19-04.html:1038)
    at a.mounted (custom_report_name_2020-11-20--13-19-04.html:1246)
    at He (vue@2.6.11:6)
    at Yt (vue@2.6.11:6)
    at Object.insert (vue@2.6.11:6)
    at k (vue@2.6.11:6)
    at a.__patch__ (vue@2.6.11:6)`

**Comment by AntyaDev** [comment] 2020-11-20 16:21
Hi @103683 how we can reproduce it?

**Comment by 103683** [comment] 2020-11-23 16:38
@AntyaDev  Hi! I don't know the STR. What kind of information can help to investigate?

- Tests runs with  .WithReportFormats(ReportFormat.Csv, ReportFormat.Html)
- Tests has two steps. In first step i made an http request and receive response.

In first step as an Reponse.Ok i return an HttpResponse object
`return result.IsSuccessStatusCode ?
                    Response.Ok(result) :
                    Response.Fail();`

In second step i receive this HttpResponse object from context, deserialize it and check some result
`context.GetPreviousStepResponse<HttpResponseMessage>();`
`return productsAvailable.Contains(true) ? Response.Ok() : Response.Fail();`

Hope this info can help.

**Comment by Yaroshvitaliy** [comment] 2020-11-24 08:00
@103683 Hi. Could you provide us such a report to investigate the issue?

**Comment by 103683** [comment] 2020-11-24 08:33
@Yaroshvitaliy  Hi! Here it is https://drive.google.com/file/d/1tMdrpL5FtphyJggqMbxA_AgSUHLyN0Up/view?usp=sharing

**Comment by Yaroshvitaliy** [comment] 2020-11-24 09:03
@103683 What browser (including version) do you use? This repot works well on Crome on my machine

**Comment by 103683** [comment] 2020-11-24 09:16
@Yaroshvitaliy  Chrome ver 86.0.4240.198 (x64). 

Trying on latest version (87.0.4280.66) - same issues.
Trying to open in Edge browser (ver 87.0.664.47) - same issues.
Firefox 83.0 - same issues.

Windows 10, ver 1909

**Comment by Yaroshvitaliy** [comment] 2020-11-24 09:18
@103683 Could you please also show how the scenario is set up in the code to reproduce the issue?

**Comment by 103683** [comment] 2020-11-24 09:32
@Yaroshvitaliy  Method TestScenario() which

return ScenarioBuilder
                .CreateScenario(scenarioName, step1, step2)
                .WithInit(ScenarioInit)
                .WithClean(ScenarioTearDown);

And another method with NUnit [Test] attribute

[Test]
public void MethodName()
{
        var scenario = TestScenario();
        var sinks = new List<IReportingSink>();

        if (ConfigBuilder.InfluxDbActive)
        {
            _influxDbSink = MyInfluxDbSink;
            sinks.Add(_influxDbSink);
        }

        NBomberRunner
            .RegisterScenarios(scenario)
            .LoadConfig(GetConfigPathFromEnvVariable() + config + ".json")
            .WithReportingSinks(
                reportingSinks: sinks.ToArray(),
                sendStatsInterval: TimeSpan.FromSeconds(1)
            )
            .WithReportFormats(ReportFormat.Csv, ReportFormat.Html)
            .WithReportFolder(ConfigBuilder.ReportsDir)
            .WithReportFileName("ReportFileName")
            .Run();
        }

**Comment by Yaroshvitaliy** [comment] 2020-11-24 09:35
@103683 Is it critical for you to set sendStatsInterval = 1 sec? 
The root cause is that there are no step stats for the first sec yet.

**Comment by 103683** [comment] 2020-11-24 10:09
@Yaroshvitaliy  I think it`s not critical to me. Really, set interval to 2 seconds and receive report without issues.

**Comment by Yaroshvitaliy** [comment] 2020-11-24 10:25
@103683 Min stats interval is 5 sec for now

**Comment by AntyaDev** [comment] 2020-11-24 16:07
Ok, I will close the issue then. We added validation on min sends stats value and in the next release.

**Closed by AntyaDev** 2020-11-24 16:07 UTC
